services:
  projectzomboid:
    environment:
      ADMIN_PWD: Changeme
      GAME_ID: 380870 -beta unstable
      PGID: '568'
      PUID: '568'
      TZ: America/Sao_Paulo
      VALIDATE: ''
    image: ghcr.io/lynkes/docker-steamcmd-server:projectzomboid
    ports:
      - "16261:16261/udp"
      - "16262:16262/udp"
      - "8766:8766/udp"
      - "8767:8767/udp"
      - "27015:27015/tcp"
    pull_policy: always
    restart: always
    volumes:
      - /mnt/vdev/apps/projectzomboid:/serverdata/serverfiles
      - /mnt/vdev/apps/steamcmd:/serverdata/steamcmd